export const GET_EVENT_STARISTIC = "GET_EVENT_STARISTIC"
export const GET_EVENT_LIST = "GET_EVENTS_LIST"
export const CREATE_EVENT_FOR_SHOP = "CREATE_EVENT_FOR_SHOP"
export const CHANGE_INFORMATION_EVENT = "CHANGE_INFORMATION_EVENT"
export const DELETE_EVENT = "DELETE_EVENT"

